FROM bitnamilegacy/spark:4.0.0
USER 0

# 1) Herramientas necesarias
RUN apt-get update && apt-get install -y \
    curl ca-certificates \
    python3 python3-pip python3-venv \
 && rm -rf /var/lib/apt/lists/*

# 2) JARs S3A pre-horneados
RUN curl -L -o /opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar \
      https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    curl -L -o /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.586.jar \
      https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.586/aws-java-sdk-bundle-1.12.586.jar

# 3) fija Python para PySpark
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3

# 4) Workspace
RUN mkdir -p /opt/etlt/app
WORKDIR /opt/etlt/app